{
  "grpcPort": "50055",
  "httpPort": "8085",
  "logLevel": 1,
  "env": "development",
  "database": {
    "name": "inquiry",
    "user": "user",
    "password": "password",
    "host": "localhost",
    "port": 5437
  },
  "s3": {
    "region": "ap-northeast-1",
      "bucket":"rvz-inquiry"
  },
  "auth":{
    "secret_key":"1asd12f"
  }
}