version: "3.1"
networks:
  net:
    driver: bridge
services:
  pg_inquiry:
    image: postgres
    environment:
      POSTGRES_DB: inquiry
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'pg_inquiry'
    volumes:
      - ./inquiry_db:/var/lib/postgresql/new/data
    ports:
      - 5437:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d inquiry" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  inquiry:
     image: inquiry
     build: ./
     ##environment:
     ##  DATABASE_URL: postgres://user:password@postgres:5432/checkout?sslmode=disable # должно быть в секретах/конфиге. Учебный пример
     ports:
      - "50051:50051"
      - "8082:8082"
#     depends_on:
#       - pg_checkout
     networks:
       - net

